version: "3.8"
services:
    kafka:
        image: iaas/kafka
        ports:
            - "9092"
        networks:
            - "local"
        #network_mode: "bridge"
        volumes:
            - "/opt/zookeeper-3.7.0/conf:/opt/zookeeper-3.7.0/conf"
            - "/opt/zookeeper-3.7.0/data:/opt/zookeeper-3.7.0/data"
            - "/opt/kafka/kafka-logs:/opt/kafka/kafka-logs"
        environment: 
            - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
            - KAFKA_ADVERTISED_HOST_NAME=kafka
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
    mqtt:
        image: iaas/mqtt
        links:
            - kafka
        ports:
            - "1883"
        networks:
            - "local"
        #network_mode: "bridge"
        volumes:
            - "/opt/mqtt:/opt/mqtt"
        environment:
            - KAFKA_MQTT_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092
            - KAFKA_MQTT_TOPIC_REGEX_LIST=mqtt-msg:.*
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
    redis:
        image: iaas/redis
        ports:
            - "6379"
        networks:
            - "local"
        #network_mode: "bridge"
        volumes:
            - "/opt/redis/data:/data"
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
    flink:
        image: iaas/flink
        links:
            - kafka
            - mqtt
            - redis
            - data-warehouse
        ports:
            - "8081"
        networks:
            - "local"
        #network_mode: "bridge"
        volumes:
            - "/opt/flink/log:/opt/flink/log"
            - "/opt/flink/data:/opt/flink/data"
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
    data-warehouse:
        image: paas/data-warehouse
        ports:
            - "51000:51000"
        networks:
            - "local"
        #network_mode: "bridge"
        volumes:
            - "/opt/data-warehouse:/opt/data-warehouse"
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
    query-platform:
        image: paas/query-platform
        links:
            - data-warehouse
        ports:
            - "52000:52000"
        networks:
            - "local"
        #network_mode: "bridge"
        volumes:
            - "/opt/query-platform:/opt/query-platform"
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
    data-layer:
        image: daas/data-layer
        links:
            - query-platform
            - redis
        ports:
            - "50000:50000"
        networks:
            - "local"
        #network_mode: "bridge"
        volumes:
            - "/opt/data-layer:/opt/data-layer"
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure

networks:
   local:
     driver: "bridge"
